[package]
name = "verse-lint"
version = "0.1.0"
edition = "2024"
description = "A linter for Epic Games' Verse language."
license = "MIT OR Apache-2.0"
repository = "https://github.com/eiei114/verse-lint"
homepage = "https://verse-lint.dev"
readme = "README.md"
keywords = ["verse", "uefn", "linter"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
